### ISSUE TITLE
Suggested improvements from Evelyn Grell

### ISSUE THREAD

**Issue by grantfirl** [NCAR/ccpp-scm#208]
The following arrived from Evelyn Grell via the RT help desk. This is copied here to remind me to address some/all of these concerns.

Messages starts here:

I just wanted to report back on a couple of things that I ran into while using the UFS_IC_generator.py script to create initial conditions for the SCMv4.0.

I ran using specified i,j points, and a specified tile.

Caveats: a) I am using an older dataset (2014 case), and the 3d model was run by someone else, so perhaps there is something different about those files.
b) my python skills are extremely limited.

1) The first issue occurred at line 1542 in the UFS_IC_generator.py script -- "'filename' referenced before assignment"
This occurred because the script was searching for the *grid.tile*.nc file in the in_dir directory, and mine was in the grid_dir directory.
When I copied my C768_grid.tile.3.ncl from the "fix" directory to the input directory, I got a few lines further.

2) line 1547 -- basically the same problem as #1 -- the script is looking for file oro_data in the in_dir, while mine was in the grid_dir.  But one more issue here.... 
For the oro_data file, the filename_pattern is:
    filename_pattern = 'oro_data.tile{0}.nc'.format(tile)              (line 485)
But I think there should be a * before oro (ie. *oro_data.tile{0}.nc)
because the files I had were called, eg. C768_oro_data.tile3.nc
So, I copied the  C768_oro_data.tile3.nc  from the "fix" directory to my input directory and called it  oro_data.tile3.nc
and that worked.

The documentation noted that for the example, the input directory was the same as the grid directory, so that is probably why these issues did not show up when you tested.
I chose to move the files rather than change the script, but I am reporting back because I expect you would rather change the script for the next release (or change the documentation to specify the correct location of the files).  (All assuming caveat (a) is not the real problem)

Otherwise, the SCM has been working pretty well for me.  Unfortunately, it is not doing a great job of reproducing the 3D results, but I have no forcing, so that is not a huge surprise.

I would like to make 2 unsolicited suggestions for minor changes for a future release:
1) For the documentation -- it would be helpful to have a brief subsection that describes the changes needed to use some existing physics package in a new suite.  For example, I used the v15p2 suite but changed the microphysics scheme to Thompson.  All the code already exists, but I had to make a SDF, change a couple of scripts, and recompile.
2) In my opinion, it would be better if the default output location was not under the bin directory.  I always move it up a directory level or two so that it would not be lost if recompiling is necessary.

Hope that is helpful!  And thank you!
Evelyn

**Comment by dustinswales** [comment]
@grantfirl
It seems that these issues have been resolved?
@egrell 
I know this is a blast from the past, but we're trying to address and cleanup any outstanding issues. Do you still have any issues using UFS_IC_generator.py?
