### ISSUE TITLE
Moving the data files to a submodule?

### ISSUE THREAD

**Issue by nbren12** [NCAR/ccpp-scm#220]
Hi! I wanted to start by thanking you for making this excellently documented tool available. I've been running the model successfully, but I have been noticing some potential improvements that would make this easier to use, especially for docker + cloud workflows.

It take long time to checkout this repository because it includes many large binary data files in `scm/data`. This makes it pretty slow to download the code quickly and poke around. Also, it prevents users developing their own more efficient/more parsimonious ways of provisioning the data-files at runtime, we have been using https://github.com/VulcanClimateModeling/fv3config/ to do this for FV3 workflows. Also, conceivably someone may want to change this data or add new cases for some experiment, in which case the git repo will be holding multiple versions of the datafiles, which could lead to further repo bloat.

Would you consider removing the data files from this repo? Moving it to a submodule would be a minimal change to the current workflow or you could host it on some HTTP server and provide a `download_data.sh` script. Unfortunately, it's pretty tricky to remove large files from git history, but I have followed this [answer](https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository) on my own work in the past.

**Comment by nbren12** [comment]
dump.

**Comment by grantfirl** [comment]
@nbren12 thanks for reaching out. Yes, I have considered doing this, especially as more cases/data are added. I researched some places that provide scientific data storage in the cloud a while back, but didn't decide on any particular service. The initial checkout is definitely taking a while these days!

**Comment by nbren12** [comment]
Github seems like a decent hosting service if you like it. It's a bit faster to download the source tarballs than to checkout the repo. I am not sure if they start charging for bandwidth. Zenodo is pretty good too and free.

Unfortunately to remove the large data files, you will really need to rewrite the whole commit lineage of master, so it's definitely better to do this sooner than later. I used this tool to do this on my own fork: https://github.com/newren/git-filter-repo.

**Comment by grantfirl** [comment]
This issue was fixed by @mkavulich when he removed large data files from the repo (which are now downloadable via GitHub release assets  -- can be moved to a different place later) and rewrote history so that repository actions (clone, etc.) are faster. Data can be retrieved using the `contrib/get_all_static_data.sh` script.

**Comment by nbren12** [comment]
That's great. Thanks for the followup.
