### ISSUE TITLE
Diagnostics clearing order

### ISSUE THREAD

**Issue by grantfirl** [NCAR/ccpp-scm#227]
The order of operations of diagnostics clearing is causing a problem where they are being written out AFTER being cleared and filled for one timestep. Therefore, as the code sits today, when n_itt_diag /= 1, the diagnostic variables that are written out are incorrect. This can be corrected by changing GFS_phys_time_vary modulo statements back to 1 from 0 -- need to verify that this change doesn't break other functionality.

**Comment by dustinswales** [comment]
@grantfirl 
Can we close this? (https://github.com/NCAR/ccpp-scm/commit/8575a0fe0e44172fa68e137c3493fcd42690b34d)
