### ISSUE TITLE
unable to follow tutorial with singularity on hpc 

### ISSUE THREAD

**Issue by ngam** [NCAR/ccpp-scm#271]
Hi, I have tried to follow the [tutorial](https://dtcenter.org/ccpp-scm-online-tutorial) using Singularity, but I couldn't get it to work as the tutorial shows. Could you please look into this and let me know if I am doing something wrong or if additional support is required for Singularity?

1. I made a directory and set the path, `export SCM_WORK='pwd' `
2. `singularity pull docker://dtcenter/ccpp-scm:v5.0.0-tutorial`
3. `export OUT_DIR=/path/to/output`
4. I tried a variety of Singularity calls, e.g. `singularity shell ccpp-scm_v5.0.0-tutorial.sif` and `singularity run ccpp-scm_v5.0.0-tutorial.sif` and `singularity exec --bind ${OUT_DIR}:/home ../ccpp-scm_v5.0.0-tutorial.sif` 
5. Once the Singularity image is activated (e.g. `Singularity>` prompt), I couldn't find the correct folders in the tutorial; that is, `cd $SCM_WORK/ccpp-scm/ccpp/suites` didn't work. The folder `ccpp-scm` didn't exist anywhere. I even tried `find . ccpp-scm` inside and outside the image in multiple directories to no avail. 

Do I need to pull the container in a specific way? (I don't think that was part of the tutorial.) Or do I need to bind the directories in different way than `--bind`. Generally, I think it would be much more helpful to have instructions for Singularity rather than Docker due to sudo rights associated with the latter. 

Thank you!

**Comment by climbfuji** [comment]
@grantfirl @michelleharrold You have most experience with containers for SCM (I know you used docker, but anyway). Do you have an idea what @ngam could try? Thanks ...

**Comment by grantfirl** [comment]
@ngam I do not have any experience with Singularity, unfortunately, so I'm not going to be able to help. I suppose we can add it as a feature request to look into in the future, but we have not claimed Singularity as a supported platform since no one has asked for it before. Sorry about that!

**Comment by michelleharrold** [comment]
I haven't used Singularity with the SCM, but I have used Singularity on Cheyenne with a WRF container -- no guarantees, but early next week, I will try running the SCM container with Singularity on Cheyenne to see if I can reproduce the issue. Stay tuned.

**Comment by ngam** [comment]
Thanks all; @michelleharrold, I will try to reproduce the error myself again this weekend as well, and provide more information if I can gather any interesting findings. I am happy to help make sure these models have decent support across different platforms, @grantfirl --- after hearing @climbfuji's excellent seminar about it at GFDL, I am very keen to toy with it and I think it can be an extremely useful tool for scientists!

**Comment by ngam** [comment]
So @grantfirl --- I don't mean to be rude, but even your Docker setup actually isn't working 100% correctly. I have installed Docker on a local machine to test/entertain your claim about supporting Docker, but not supporting Singularity. The last line in the Dockerfile is `WORKDIR /comsoftware/ccpp-scm/scm/bin` and in the tutorial, it says to `cd $SCM_WORK/ccpp-scm/ccpp/suites` after executing `export SCM_WORK=`pwd`/../..`. Do you see the problem yet? 

This is not exactly an out-of-the-box solution/tutorial for someone who's not (and doesn't want to be) an expert in containerization. I think I have wasted enough time trying to make it work. And as a scientist, I have no time to moonlight as a software developer spending many hours to make inconsistent software work like it was claimed to work. In this particular instance, simply adding extra `/..` or changing `cd $SCM_WORK/ccpp-scm/ccpp/suites` to `cd $SCM_WORK/ccpp/suites` will resolve the problem. But still... not exactly a vote of confidence in this piece of instruction and thus it likely will waste much more of my time than I'm willing to waste on something potentially (but not necessarily) solving a problem. I hope you can do better.

**Comment by ngam** [comment]
For @michelleharrold --- I have looked into this again, and I am not really sure what's causing the file system builtin in the Dockerfile to disappear once triggered from Singularity. It could be an issue on the HPC I am using to run Singularity, but it is kind of bizarre. I have tried to rebuild the filesystem following the series of commands in the Dockerfile (running the scripts in `/contrib`, etc.), but I kept running into errors about permissions. 

Anyway, notwithstanding deeper issues of the filesystem being somewhat dysfunctionally disorganized (see my above comment about Docker), another workaround the whole Docker/Singularity is to convert the Dockerfile (available in the repository) into a Singularity definition file using the spython tool. One would need to install spython first, `pip install spython`, and then the conversion could be done with the following line: `spython recipe Dockerfile >> Singularity.def`. Eventually the problem with this is that one would need sudo rights to build on a given device, but Singularity offers the option of remote build for like 10 GBs or something (the building will happen on their cloud). So it should in theory work, but see below for some of the errors I got in the process when I tried it.

My request to you would be: Could you try to see if you could find a resolution so that the Docker container can simply work with Singularity? I did this in the past --- basically, I built a simple Docker container and I only used it via Singularity. At least, could you perhaps try to convert the Dockerfile into Singularity.def and then build it to see if it works? See the direct output of the spython trick below as a start. If you manage to get it to work satisfactorily (you know your software better than me!), then let me know and I will then attempt to use it. Otherwise, I don't think I should keep trying to make it work on my own. 

(cont. in next comment)

**Comment by ngam** [comment]
I did the following:
1. `pip install spython`
2. After copying the Dockerfile from your repo, `spython recipe Dockerfile >> Singularity.def` (see output at the end)
3. `singularity build --remote scm_sing Singularity.def` (this results in the [following image](https://cloud.sylabs.io/library/_container/614f4685ff2db5ba27b5c6ca) which you can pull according to the instructions there)
4. then, running the singularity container (filesystem seems okay at first) but then errors related to building, I suppose:
```bash
singularity shell --writable-tmpfs scm_sing 
Singularity> 
Singularity> pwd
/scratch/network/nm2266/scm_work
Singularity> cd /comsoftware/
ccpp-scm/ libs/     
Singularity> cd /comsoftware/ccpp-scm/scm/bin/
Singularity> ./multi_run_scm.py -c twpice
bash: ./multi_run_scm.py: No such file or directory
Singularity> ls
ccpp_prebuild.err  ccpp_prebuild.out  CMakeCache.txt  CMakeFiles
Singularity> cd ../src
Singularity> ./multi_run_scm.py -c twpice
INFO: Running all supported suites with case twpice
INFO: Executing process 1 of 5 (./run_scm.py -c twpice -s SCM_GFS_v15p2)
CRITICAL: ####### The subprocess started using the command (./run_scm.py -c twpice -s SCM_GFS_v15p2) exited with code 1. #######
Run the command (./run_scm.py -c twpice -s SCM_GFS_v15p2) by itself again or use the -v or -vv options for more details.
INFO: Executing process 2 of 5 (./run_scm.py -c twpice -s SCM_GFS_v16beta)
CRITICAL: ####### The subprocess started using the command (./run_scm.py -c twpice -s SCM_GFS_v16beta) exited with code 1. #######
Run the command (./run_scm.py -c twpice -s SCM_GFS_v16beta) by itself again or use the -v or -vv options for more details.
INFO: Executing process 3 of 5 (./run_scm.py -c twpice -s SCM_csawmg)
CRITICAL: ####### The subprocess started using the command (./run_scm.py -c twpice -s SCM_csawmg) exited with code 1. #######
Run the command (./run_scm.py -c twpice -s SCM_csawmg) by itself again or use the -v or -vv options for more details.
INFO: Executing process 4 of 5 (./run_scm.py -c twpice -s SCM_GSD_v1)
CRITICAL: ####### The subprocess started using the command (./run_scm.py -c twpice -s SCM_GSD_v1) exited with code 1. #######
Run the command (./run_scm.py -c twpice -s SCM_GSD_v1) by itself again or use the -v or -vv options for more details.
INFO: Executing process 5 of 5 (./run_scm.py -c twpice -s SCM_RRFS_v1alpha)
CRITICAL: ####### The subprocess started using the command (./run_scm.py -c twpice -s SCM_RRFS_v1alpha) exited with code 1. #######
Run the command (./run_scm.py -c twpice -s SCM_RRFS_v1alpha) by itself again or use the -v or -vv options for more details.
Singularity> 
Singularity> 
```
(Dockerfile and Singularity.def file in the next comment)

**Comment by ngam** [comment]
```bash
$ cat Dockerfile 
FROM dtcenter/common-community-container:gnu9

MAINTAINER Michelle Harrold <harrold@ucar.edu> or Grant Firl <grantf@ucar.edu>

#
# Dockerfile for building CCPP SCM container
#

# Note: The common community container image contains the following packages, which are used to build the SCM:
# gfortran, gcc, cmake, netCDF, HDF5, ZLIB, SZIP, Python, and libxml2
# To access the common community container repository: https://github.com/NCAR/Common-Community-Container

# Obtain CCPP SCM source code
RUN cd /comsoftware \
  && git clone --recursive -b v5.0.0 https://github.com/NCAR/ccpp-scm

# Obtain the pre-computed look-up tables for running with Thompson microphysics
RUN cd /comsoftware/ccpp-scm/ \
  && . contrib/get_thompson_tables.sh
  
# Obtain the IN-CCN data for use with Morrison-Gettelman microphysics
RUN cd /comsoftware/ccpp-scm/ \
  && . contrib/get_mg_inccn_data.sh

# Run the machine setup script to set environment variables
RUN cd /comsoftware/ccpp-scm/scm/ \
  && . etc/CENTOS_docker_setup.sh

ENV bacio_ROOT /comsoftware/ccpp-scm/nceplibs
ENV sp_ROOT /comsoftware/ccpp-scm/nceplibs
ENV w3nco_ROOT /comsoftware/ccpp-scm/nceplibs

# Create your own link from python -> python3 
# This works without setting the system PATH env var
# since /usr/local/bin is before /usr/bin in the search path.
USER root
RUN ln -s /usr/bin/python3 /usr/local/bin/python
USER comuser

# Invoke cmake on the source code to build
RUN cd /comsoftware/ccpp-scm/scm \
  && mkdir bin \
  && cd bin \
  && cmake ../src \
  && make -j4

# The analysis scripts have options for using LaTeX when making figure labels.
# If you would like to install LaTeK, uncomment the section below. 
# Note: This will increase the image size by 1 GB.
#USER root
#RUN yum -y update \
#  && yum -y install texlive-*
#USER comuser

# Set working directory
WORKDIR /comsoftware/ccpp-scm/scm/bin
```

```bash
$ cat Singularity.def 
Bootstrap: docker
From: dtcenter/common-community-container:gnu9
Stage: spython-base

%labels
MAINTAINER Michelle Harrold <harrold@ucar.edu> or Grant Firl <grantf@ucar.edu>
%post


#
# Dockerfile for building CCPP SCM container
#

# Note: The common community container image contains the following packages, which are used to build the SCM:
# gfortran, gcc, cmake, netCDF, HDF5, ZLIB, SZIP, Python, and libxml2
# To access the common community container repository: https://github.com/NCAR/Common-Community-Container

# Obtain CCPP SCM source code
cd /comsoftware \
&& git clone --recursive -b v5.0.0 https://github.com/NCAR/ccpp-scm

# Obtain the pre-computed look-up tables for running with Thompson microphysics
cd /comsoftware/ccpp-scm/ \
&& . contrib/get_thompson_tables.sh
  
# Obtain the IN-CCN data for use with Morrison-Gettelman microphysics
cd /comsoftware/ccpp-scm/ \
&& . contrib/get_mg_inccn_data.sh

# Run the machine setup script to set environment variables
cd /comsoftware/ccpp-scm/scm/ \
&& . etc/CENTOS_docker_setup.sh

bacio_ROOT=/comsoftware/ccpp-scm/nceplibs
sp_ROOT=/comsoftware/ccpp-scm/nceplibs
w3nco_ROOT=/comsoftware/ccpp-scm/nceplibs

# Create your own link from python -> python3 
# This works without setting the system PATH env var
# since /usr/local/bin is before /usr/bin in the search path.
su -  root # USER root
ln -s /usr/bin/python3 /usr/local/bin/python
su -  comuser # USER comuser

# Invoke cmake on the source code to build
cd /comsoftware/ccpp-scm/scm \
&& mkdir bin \
&& cd bin \
&& cmake ../src \
&& make -j4

# The analysis scripts have options for using LaTeX when making figure labels.
# If you would like to install LaTeK, uncomment the section below. 
# Note: This will increase the image size by 1 GB.
#USER root
#RUN yum -y update \
#  && yum -y install texlive-*
#USER comuser

# Set working directory
cd /comsoftware/ccpp-scm/scm/bin

%environment
export bacio_ROOT=/comsoftware/ccpp-scm/nceplibs
export sp_ROOT=/comsoftware/ccpp-scm/nceplibs
export w3nco_ROOT=/comsoftware/ccpp-scm/nceplibs
%runscript
cd /comsoftware/ccpp-scm/scm/bin
exec /bin/bash "$@"
%startscript
cd /comsoftware/ccpp-scm/scm/bin
exec /bin/bash "$@"
```

(As you see, the differences are minimal. Anyway, it would be good to have a fully functioning tutorial/container --- thanks!)

**Comment by ngam** [comment]
I had written a few back-and-forth comments over the weekend, and I believe I found a resolution to this issue. I decided to delete my previous comments and instead submit a pull request with the resolution. I am happy to help further if you'd like. In particular, 

1. the tutorial doesn't actually work out-of-the-box because of minor mistakes in the environment and path settings --- I will be happy to provide corrections for those and submit another pull request; and
2. the file structure inside the container isn't the most productive or efficient --- ideally, there should be clear "workspace" folder mounted where the user will have read/write access, but read-only access to the rest of the structure inside the container (e.g. `... /ccpp-scm/ ...`), and as such the user won't need to edit any source code within the container or have write access to some folders in order to go through the tutorial. 

For the most part, one should be absolutely able to work with a Docker container in Singularity without friction. For example, one could easily swap `docker pull dtcenter/ccpp-scm:v5.0.0-tutorial` with `singularity pull docker://dtcenter/ccpp-scm:v5.0.0-tutorial` and no issue would occur. Hence, the comment about "not providing support for Singularity" is quite unproductive and uninformed. See? In the end, this was a deeper issue with the container and not with the Docker--Singularity interoperability. 

One last comment: It is really important to get this 100% right, and not just 90%. An example, at GFDL, we don't have access to any machine that would have all the necessary prerequisites to run this model natively. Hence, the need for a container. And if this container isn't 100% portable, then what's the point of it? And if scientists like me spend a lot of time simply trying to make things work, then they will likely not make any use of this. 

Thank you for your attention to this, and I am looking forward to using this framework in the coming months, and potentially helping you iron out some of the remaining 10% of this to make it truly accessible to non-developers.

**Comment by grantfirl** [comment]
@ngam Thanks for discovering the error in the tutorial instructions regarding setting the $SCM_WORK variable when using Docker. From (https://dtcenter.org/ccpp-scm-online-tutorial/download-build/option-2-using-docker-container), if one changes `export SCM_WORK=pwd/../..` to `export SCM_WORK=`/comsoftware` the rest of the tutorial works for me. I've asked for this to be corrected on the webpage.

Regarding your second suggestion, since part of the purpose of the tutorial is to teach editing source code to work with the CCPP (for a user's individual purpose) and files in several directories need to be edited to follow the tutorial, having one read/write "workspace" seems like more work to me. Are you suggesting this because some users will not want to edit code in a terminal and would prefer to edit code using their choice of editor on their host system? Perhaps I'm not understanding the motivation.

Regarding Singularity, apologies for being "uninformed". I have never had cause to learn it. Perhaps someone with Singularity on their system can try your PR and/or rework the Dockerfile to be compatible. In the meantime, did you have any further trouble using the Docker instructions (once correctly the $SCM_WORK environment variable)?

**Comment by ngam** [comment]
Thanks, I didn't have any further trouble with Docker because I stopped at the first mistake... I think it would make more sense to not set up these environmental paths anyway, but I'd leave that to you since you know significantly more about this than my limited focus. The only remaining issue (besides using corrected / absolute paths) is the filesystem, otherwise, the container will remain somewhat limited. 

For the motivation, I am not a containerization expert, but I suppose writing inside a container filesystem usually requires sudo rights. At least from my reading of the Singularity documentation, it is highly discouraged; it also leads to potential lack of transparency --- do you know what I mean? Basically, the idea of a container is for it to just work and provide one an alternative OS, so to speak. If you use that OS to edit the source files, then you're essentially changing the container at a deeper level. But I completely understand your own motivation (to have this mostly aimed at developers) and your current setup may make sense for that. However, are developers your own only audience? At least, that's not my impression! I do agree though that is more work, and of course, if you don't have time to implement it, a note about alternative ways to implement should suffice for now.

About Singularity operability: It just widens the audience net. Again, everyone can install Docker and play with it, but not many scientists would want to install Docker on their personal machines. I gave you the example of GFDL --- I can only use Docker on my personal machine; on all my work machines and HPCs, I cannot use Docker. So really, my point here is: I think it is important for you to offer standard and tested Singularity support. Besides, do you anticipate a local machine will suffice for a production run of this (i.e. beyond a toy problem)? I am thinking of using SCM coupled with a machine learning model to improve the parameterizations, and I don't think my personal machine will be able to handle either!

From a software standpoint, is the goal of this project to fork it and then remake it or to just use it? I guess, I understand your setup motivation if the former, but I am not sure I understand it from a usability standpoint. My intermediate plan was to fork it and then revamp your container to suit my needs, but I wanted to be able to just use your container without having to edit it.

Sorry for being sloppy with words --- I didn't mean to imply "uninformed" as an insult: It was just my understanding that the interoperability between Docker and Singularity was near frictionless. Also, fwiw, I haven't succeeded in installing Singularity on my local machine after weeks of trying! So I would like to make clear: I don't recommend installing it on a local machine --- it's just that on HPCs, I have no other option 😞
