### ISSUE TITLE
Problem to install a shapely python module

### ISSUE THREAD

**Issue by wzzheng90** [NCAR/ccpp-scm#298]
I got a problem when I set the environment variables for CCPP-SCM on Hera with icc/ifort as follows:

    % source scm/etc/Hera_setup_intel.csh

"Hera_setup_intel.csh" needs to install a shapely python module:
  
      pip install --index-url http://anaconda.rdhpcs.noaa.gov/simple --trusted-host [anaconda.rdhpcs.noaa.gov](http://anaconda.rdhpcs.noaa.gov/) shapely --user

The error message shows:
        Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.HTTPConnection object at 0x7f8d26951828>, 'Connection to [anaconda.rdhpcs.noaa.gov](http://anaconda.rdhpcs.noaa.gov/) timed out. (connect timeout=15)')': /simple/shapely/

How to fix this problem?   Thanks!!

Weizhong

**Comment by grantfirl** [comment]
Hi Weizhong, I'll look into it and make any changes to the Hera setup script as necessary.

**Comment by wzzheng90** [comment]
@grantfirl :  Really appreciate!!

**Comment by grantfirl** [comment]
@wzzheng90 Take a look at #299. Would you try to modify your Hera_setup_intel.csh file and see if this solution works for you?

**Comment by wzzheng90** [comment]
@grantfirl :   Try this command:   source scm/etc/Hera_setup_intel.csh   and the message shows as follows:

Setting environment variables for CCPP-SCM on Hera with icc/ifort
Loading intel and netcdf modules...
Setting CC/CXX/FC environment variables
Setting NCEPLIBS environment variables
Loading cmake
Loading the SCM python environment
.: Permission denied.
conda: Command not found.

**Comment by wzzheng90** [comment]
All right.  I just saw you changed it again "source /scratch1/BMC/gmtb/SCM_anaconda/etc/profile.d/conda.csh".
Now type:   source scm/etc/Hera_setup_intel.csh   and no error message appears:

Setting environment variables for CCPP-SCM on Hera with icc/ifort
Loading intel and netcdf modules...
Setting CC/CXX/FC environment variables
Setting NCEPLIBS environment variables
Loading cmake
Loading the SCM python environment

=======  
However, when I compile the code, error messages show as follows:

~/ccpp-scm/ccpp/physics/physics/cires_tauamf_data.F90(1): error #7001: Error in creating the compiled module file.   [CIRES_TAUAMF_DATA]
module cires_tauamf_data
compilation aborted for  ~/ccpp-scm/ccpp/physics/physics/cires_tauamf_data.F90 (code 1)
make[2]: *** [ccpp/physics/CMakeFiles/ccpp_physics.dir/physics/cires_tauamf_data.F90.o] Error 1
make[1]: *** [ccpp/physics/CMakeFiles/ccpp_physics.dir/all] Error 2
make: *** [all] Error 2

**Comment by grantfirl** [comment]
The compilation error is really strange because nothing in the actual code changed and the compiler and NCEPLIBS setup stayed the same too.

**Comment by wzzheng90** [comment]
I try it again (source scm/etc/Hera_setup_intel.csh ) and now more lines show as follows:

Setting environment variables for CCPP-SCM on Hera with icc/ifort
Loading intel and netcdf modules...
Setting CC/CXX/FC environment variables
Setting NCEPLIBS environment variables
Loading cmake
Loading the SCM python environment
usage: conda [-h] [-V] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:
......
==================================
Then, I compile the code and it is working !!   
Also, I try a couple of cases, all work fine.
Thanks a lot !!!
