### ISSUE TITLE
Need to update the SCM Users Guide for v6 release

### ISSUE THREAD

**Issue by ligiabernardet** [NCAR/ccpp-scm#309]
Need to update the SCM Users Guide for v6 release. Some of the specific aspects that need update are:

- Build with HPC Stack (with or without SPACK - likely without) instead of NCEPLIBS.
- Please add other aspects here
- Who? Potentially new NCAR SE, TBD after 4/18 starting date. Possibly with Grant's guidance and Dom's and others' review.

**Comment by grantfirl** [comment]
This was completed as part of the v6 release.
