### ISSUE TITLE
Bug fix for reading sfc fluxes (DEPHYv1)

### ISSUE THREAD

**Issue by hertneky** [NCAR/ccpp-scm#427]
Surface fluxes are not read correctly when running the SCM using DEPHYv1 format.

This issue was uncovered from LSM testing from Xia Sun awhile ago. I had mistakenly though that Grant had pulled the fixes into a PR he had open at the time. The issue was uncovered again when @egrell was attempting to run the DEPHY MPACE case.

**Comment by dustinswales** [comment]
@hertneky Can you add some details to the issue? (e.g. How did you identify the problem?)

**Comment by hertneky** [comment]
@dustinswales I added more details. Evelyn tested the fixes with MPACE, but I will also test with the ISDAC DEPHY case

**Comment by mzhangw** [comment]
The issue in coupling to LSM was reported by Dr. Xia Sun from GSL, but not from me.

**Comment by hertneky** [comment]
@mzhangw You are absolutely right! My mistake!
