### ISSUE TITLE
Decide on SDFs for release? - Grant, Dustin, Weiwei

### ISSUE THREAD

**Issue by scrasmussen** [NCAR/ccpp-scm#448]
> Question: which physics and suites to support and what shall we call them?
>
> **Highlighted** name -> responsible person
> Open ones will be completed by PRs
> - [X] HR3 - create (**Weiwei** will submit PR for SDF and namelist options)
> - [x] HR3 with RRTMGP - create SDF and namelist options (**Dustin**)
> - [x] RRFS v1 - (actually HRRR GF) create - create SDF and namelist options (**Dustin, Grant**) named: FV3_HRRR_GF
> - [X] GFS v16 - in SCM already
> - [X] WoFS - in SCM already
> 
> **Mike K** will come up with a proposal for names

**Comment by bluefinweiwei** [comment]
HR3 PR submitted: [https://github.com/NCAR/ccpp-scm/pull/445]

**Comment by dustinswales** [comment]
HR3 w/ RRTMGP PR submitted https://github.com/NCAR/ccpp-scm/pull/462

**Comment by dustinswales** [comment]
This has been addressed and can be closed once #474 and #467 are merged.

**Comment by dustinswales** [comment]
Completes
