### ISSUE TITLE
Determine which scientific tests need to be run so we make sure everything is working as expected, including replay

### ISSUE THREAD

**Issue by scrasmussen** [NCAR/ccpp-scm#450]
From @ligiabernardet 
> Run every case of subsets?
> 
> - [ ] Include canned test case/replay case - this should already be done as part of the CI
> - [ ] Visually look at the CI output to make sure it looks good
> - [ ] Add more DEPHY cases to cover more options (e.g. prescribed fluxes) - 1 from each campaign as long as the setup is the same
> - [ ] Replay testing workflow

**Comment by dustinswales** [comment]
I will 
- update the staged UFS RT data to include dynamic tendencies on the DTC FTP server
- Expand CI script for replay to due entire workflow 
- Move to DEPHY cases suggested buy Weiwei

**Comment by dustinswales** [comment]
Done.
