### ISSUE TITLE
Run scientific tests

### ISSUE THREAD

**Issue by scrasmussen** [NCAR/ccpp-scm#451]
Run testcases to make sure output makes sense.

**Comment by dustinswales** [comment]
#475 Includes plots of all SCM output for all supported cases and suites.
Once #467 and #474 are merged, #475 will create plots for the three new SDFs (HR3, HR3_RRTMGP, RRFS_v1), in addition to the unchanged configurations (GFS_v16 and WoFS). 

*ToDo* Someone needs to compare the HR3/HR3_RRTMGP/RRFS_v1 plots to the GFS_v16/WoFS plots to ensure these configurations aren't out to lunch.

**Comment by dustinswales** [comment]
Done.
