### ISSUE TITLE
New cases and case formatting

### ISSUE THREAD

**Issue by scrasmussen** [NCAR/ccpp-scm#454]
From @ligiabernardet 
> - MOSAiC from Amy Solomon - Amy said this will be ready soon... (**Tracy**)
> - COMBLE from Weiwei - Do we need approval to add to our repo? Probably not. (**Weiwei** will push when ready)
> - Repo (not necessarily code repo) to hold cases - if data not that large, maybe github is okay? Currently case data is a tarball on github, but separate from scm repo.  Finding another platform for hosting as they are kinda large.
> - Redo existing proprietary cases in DEPHY format - **Grant** can volunteer to help with this.
> - "Save" interesting UFS replay cases and provide avenue for users to do the same? (as well as avenue to document cases)

**Comment by dustinswales** [comment]
Done.
