### ISSUE TITLE
Add new RTs for v7 SDFs

### ISSUE THREAD

**Issue by dustinswales** [NCAR/ccpp-scm#469]
Expand rt_test_cases.py to include new v7 SDFs.
https://github.com/NCAR/ccpp-scm/blob/main/test/rt_test_cases.py

**Comment by scrasmussen** [comment]
Issue completed in [PR#496](https://github.com/NCAR/ccpp-scm/pull/496/files#diff-931c4ab4da106e4eed5d7301d9957d9e535f2ddf0b13329198f2d1d7ddb0ae50)
