### ISSUE TITLE
Expand DEPHY CI test

### ISSUE THREAD

**Issue by dustinswales** [NCAR/ccpp-scm#470]
We have a separate CI test that uses [the DEPHY repository](https://github.com/GdR-DEPHY/DEPHY-SCM), but there aren't any comparisons in that test, it just ensures the SCM works with the DEPHY repo. When I set this up I didn't do a deep evaluation on the case from the DEPHY repo, just more of a technical test that the SCM could use the latest and greatest DEPHY cases. 
@bluefinweiwei  has used the SCM with cases in the DEPHY repo for T&E, so I think it makes more sense to use a case that she is confident in. And then add a comparison step to the DEPHY CI test.

**Comment by dustinswales** [comment]
@bluefinweiwei Just let me know which case we should use and I'll update the script.

**Comment by bluefinweiwei** [comment]
Thanks for asking! Perhaps several cases that our team is currently running: ISDAC, MPACE, DYNAMO, MAGIC, and [COMBLE (I just pushed a PR to our repo)](https://github.com/NCAR/ccpp-scm/pull/463) attn: @hertneky

**Comment by dustinswales** [comment]
Completed.
