### ISSUE TITLE
No t2m output

### ISSUE THREAD

**Issue by meteorids** [NCAR/ccpp-scm#543]
I am running CCPP v7, arm_sgp_summer_1997_A and B, bomex, and twice cases with GFS17_p8 and GFS16 on Hera. 
For the ARM and bomex cases I get no t2m output, only for the twpice case.
Please advise.

**Comment by hertneky** [comment]
Thanks for bringing this to our attention. I would think t2m "should" in theory be able to be output by all these cases.

The common difference I see in the forcing file for the 3 cases that do not output t2m vs the twpice case which does output t2m, is the surface_forcing_temp. For the 3 cases that do not output t2m, the kinematic sfc flux (wpthetap) is prescibed, while twpice uses prescribed surface temperature (ts_forc).

t2m is not computed within the SCM, but rather comes from the physics from what I see. I can look more at it, but perhaps @grantfirl or @dustinswales can comment more on this.

**Comment by meteorids** [comment]
Thank you for your response! 
The issue got resolved. I am unsure what solved it, but I have the desired output now.

**Comment by meteorids** [comment]
Thank you for your response!
The issue got resolved. I am unsure what solved it, but I have the desired output now.

**Comment by meteorids** [comment]
Thank you for your response!
After more experimentation, it seems like the same issue still stands.

**Comment by meteorids** [comment]
I made ran the SGP-A and TWPICE cases with the GFS16 and GFS_v17_p8_ugwpv1 suits and the the issue persists.
